alias grep="grep --color=auto"
alias la="ls -la --color=auto"
alias ll="ls -l --color=auto"
alias ls="ls --color=auto"
alias maxprompt="export PROMPT_SIZE=\"max\""
alias midprompt="export PROMPT_SIZE=\"mid\""
alias minprompt="export PROMPT_SIZE=\"min\""