alias grep="grep --color=auto"
alias la="ls -Fahl --color=auto"
alias ll="ls -Fhl --color=auto"
alias ls="ls -F --color=auto"
alias maxprompt="export PROMPT_SIZE=\"max\""
alias midprompt="export PROMPT_SIZE=\"mid\""
alias minprompt="export PROMPT_SIZE=\"min\""